# Type stubs for fox_agent_sdk._core — auto-generated Rust bindings.

from __future__ import annotations
from typing import Any, Final


# ── Provider / Config ────────────────────────────────────────────────────

class ProviderConfig:
    """LLM provider configuration (base URL / API key / model routing)."""
    @staticmethod
    def deepseek(api_key: str) -> ProviderConfig: ...
    @staticmethod
    def openai(api_key: str) -> ProviderConfig: ...
    @staticmethod
    def anthropic(api_key: str) -> ProviderConfig: ...
    @staticmethod
    def custom(
        provider_name: str, base_url: str, api_key: str, *, timeout_secs: int = 120
    ) -> ProviderConfig: ...


class SafetyConfig:
    """Permission / safety policy configuration."""
    def __init__(self, default_policy: str, productive_tool_confirm: bool) -> None: ...


class SdkConfig:
    """Top-level SDK configuration (equivalent to agent.toml)."""
    @staticmethod
    def from_file(path: str) -> SdkConfig: ...


# ── Agent Builder ────────────────────────────────────────────────────────

class AgentBuilder:
    """Fluent builder for creating configured Agent instances."""
    def __init__(self) -> None: ...
    def provider_config(self, config: ProviderConfig) -> None: ...
    def sdk_config_file(self, path: str) -> None: ...
    def sdk_config(self, config: SdkConfig) -> None: ...
    def model_id(self, id: str) -> None: ...
    def working_dir(self, dir: str) -> None: ...
    def with_default_tools(self) -> None: ...
    def with_tool(self, tool: Any) -> None: ...
    def with_mcp_server(self, config: McpServerConfig) -> None: ...
    def with_session_store(self, store: FileSessionStore) -> None: ...
    def with_safety_policy(self, config: SafetyConfig) -> None: ...
    def with_system_prompt(self, template: str) -> None: ...
    async def build(self) -> Agent: ...


# ── Agent ────────────────────────────────────────────────────────────────

class Agent:
    """The main Agent runtime.  Created via AgentBuilder.build()."""
    @property
    def session_id(self) -> str: ...
    @property
    def skill_registry(self) -> SkillRegistry: ...
    def run(self, prompt: str) -> EventStream: ...
    def resume(self, allow: bool) -> EventStream: ...
    async def snapshot(self) -> SessionSnapshot: ...


# ── Event Stream ─────────────────────────────────────────────────────────

class EventStream:
    """Async iterator that yields Agent events as dicts."""
    def __aiter__(self) -> EventStream: ...
    async def __anext__(self) -> dict[str, Any]: ...


# ── Tool System ─────────────────────────────────────────────────────────────

class ToolContext:
    """Context passed to custom Python tool `execute()` calls."""
    @property
    def session_id(self) -> str: ...
    @property
    def working_dir(self) -> str: ...
    @property
    def project_dir(self) -> str: ...


class ToolOutput:
    """Return value from a custom Python tool."""
    def __init__(self, text: str = "", *, is_error: bool = False, json: str | None = None) -> None: ...
    @staticmethod
    def error(text: str) -> ToolOutput: ...
    @property
    def text(self) -> str: ...
    @property
    def is_error(self) -> bool: ...


class Tool:
    """Abstract base for custom Python tools."""
    ...


# ── MCP ─────────────────────────────────────────────────────────────────────

class McpServerConfig:
    """MCP (Model Context Protocol) server connection configuration."""
    @staticmethod
    def stdio(name: str, command: str, args: list[str] | None = None) -> McpServerConfig: ...
    @staticmethod
    def sse(name: str, url: str) -> McpServerConfig: ...
    @staticmethod
    def streamable_http(name: str, url: str) -> McpServerConfig: ...


class McpTransportMode:
    """Transport mode constants for MCP connections."""
    STDIO: Final = "stdio"
    SSE: Final = "sse"
    STREAMABLE_HTTP: Final = "streamable_http"


# ── Memory ──────────────────────────────────────────────────────────────────

class MemoryConfig:
    """Configuration for the cross-session memory / LLM-wiki system."""
    def __init__(self, *, enabled: bool = False, auto_extract: bool = False, ...) -> None: ...
    @property
    def enabled(self) -> bool: ...


class MemoryScope:
    """Scope constants for memory operations."""
    SESSION: Final = "session"
    PROJECT: Final = "project"
    GLOBAL: Final = "global"
    ALL: Final = "all"


class RecallMode:
    """Recall strategy constants."""
    RECENT: Final = "recent"
    KEYWORD: Final = "keyword"
    WIKI: Final = "wiki"


class MemoryManager:
    """Cross-session memory: CRUD + recall + semantic search."""
    def __init__(self, config: MemoryConfig) -> None: ...
    def with_storage_dir(self, dir: str) -> MemoryManager: ...
    def with_project_dir(self, dir: str) -> MemoryManager: ...
    def with_session_id(self, id: str) -> MemoryManager: ...
    def wiki_enabled(self) -> bool: ...
    def remember(self, content: str, *, category: str = "fact", scope: str = "project") -> str: ...
    def recall(self, query: str | None, *, limit: int = 10, mode: str = "keyword", scope: str = "all") -> dict: ...
    def search(self, text: str, *, scope: str = "all") -> dict: ...
    def list(self, scope: str = "all") -> dict: ...
    def forget(self, id: str) -> bool: ...


# ── Session ─────────────────────────────────────────────────────────────────

class FileSessionStore:
    """File-backed session store."""
    def __init__(self, base_dir: str) -> None: ...


class SessionSnapshot:
    """Read-only snapshot of a persisted agent session."""
    @property
    def session_id(self) -> str: ...
    @property
    def turn_count(self) -> int: ...


# ── Skills ────────────────────────────────────────────────────────────────

class Skill:
    """A Claude Code-compatible skill."""
    @property
    def name(self) -> str: ...
    @property
    def description(self) -> str: ...
    @property
    def prompt(self) -> str: ...
    @property
    def allowed_tools(self) -> list[str]: ...
    @property
    def model(self) -> str | None: ...
    @property
    def version(self) -> str | None: ...


class SkillRegistry:
    """Registry of loaded skills."""
    def list(self) -> list[Skill]: ...
    def get(self, name: str) -> Skill | None: ...


# ── Evaluation ────────────────────────────────────────────────────────────

class JudgeScores:
    """Scores assigned by the LLM judge."""
    @property
    def completeness(self) -> int: ...
    @property
    def solution_quality(self) -> int: ...
    @property
    def error_recovery(self) -> int | None: ...
    @property
    def redundancy(self) -> int: ...
    def weighted_average(self) -> float: ...


class EvalReport:
    """Evaluation report built from an agent's session events."""
    def __init__(self, task_id: str, user_prompt: str, agent_response: str, events: list[dict], assertions_passed: bool) -> None: ...
    @property
    def task_id(self) -> str: ...
    @property
    def user_prompt(self) -> str: ...
    @property
    def agent_response(self) -> str: ...
    @property
    def assertions_passed(self) -> bool: ...


class TaskJudge:
    """LLM-as-Judge evaluator."""
    def __init__(self, provider_config: ProviderConfig, model_id: str) -> None: ...
    def evaluate(self, report: EvalReport) -> JudgeScores: ...


class RuleSeverity:
    """Severity level constants."""
    WARNING: Final = "warning"
    ERROR: Final = "error"


class RuleViolation:
    """A single behavior rule violation."""
    rule_name: str
    message: str
    severity: str


class BehaviorRuleEngine:
    """Engine that checks agent event streams for known anti-patterns."""
    def __init__(self) -> None: ...
    def check(self, events: list[dict]) -> list[RuleViolation]: ...
    def check_errors(self, events: list[dict]) -> list[RuleViolation]: ...


class CommandAssertion:
    """Defines a command to run and its expected outcome."""
    def __init__(self, command: str, *, working_dir: str = ".", expected_exit_code: int = 0, stdout_contains: str | None = None, stderr_not_contains: str | None = None) -> None: ...


class TaskAssertions:
    """World-state assertions to verify agent task completion."""
    def __init__(self) -> None: ...
    def file_exists(self, path: str) -> None: ...
    def file_contains(self, path: str, substring: str) -> None: ...
    def file_not_contains(self, path: str, substring: str) -> None: ...
    def dir_exists(self, path: str) -> None: ...
    def command(self, cmd: CommandAssertion) -> None: ...
    def max_duration(self, secs: int) -> None: ...
    def run(self, working_dir: str) -> AssertionReport: ...


class AssertionReport:
    """Report from running task assertions."""
    @property
    def passed(self) -> bool: ...
    @property
    def total(self) -> int: ...
    @property
    def passed_count(self) -> int: ...
    @property
    def failures(self) -> list[str]: ...


# ── Hooks ────────────────────────────────────────────────────────────────

class HookEvent:
    """Lifecycle event constants for hook triggers."""
    SESSION_START: Final = "session-start"
    USER_PROMPT_SUBMIT: Final = "user-prompt-submit"
    PRE_TOOL_USE: Final = "pre-tool-use"
    POST_TOOL_USE: Final = "post-tool-use"
    NOTIFICATION: Final = "notification"
    STOP: Final = "stop"
    SUBAGENT_STOP: Final = "subagent-stop"
    PRE_COMPACT: Final = "pre-compact"
    PERMISSION_PROMPT: Final = "permission-prompt"
    PRE_FILE_WRITE: Final = "pre-file-write"
    POST_FILE_WRITE: Final = "post-file-write"


class HooksConfig:
    """Configuration for the hooks system."""
    def __init__(self, *, enabled: bool = True, timeout_secs: int = 30, max_concurrent: int = 5, load_global: bool = True) -> None: ...
    def add_directory(self, dir: str) -> None: ...


# ── Plugins ──────────────────────────────────────────────────────────────

class PluginsConfig:
    """Configuration for the plugins system."""
    def __init__(self, *, enabled: bool = True, auto_update_hours: int = 0) -> None: ...
    def add_preinstall(self, name: str) -> None: ...
    def add_marketplace(self, name: str, url: str, source: str, *, owner: str | None = None, repo: str | None = None) -> None: ...


class PluginManifest:
    """Metadata for an installed plugin (read-only)."""
    @property
    def name(self) -> str: ...
    @property
    def version(self) -> str | None: ...
    @property
    def description(self) -> str | None: ...
    @property
    def author(self) -> str | None: ...


# ── Swarm ────────────────────────────────────────────────────────────────

class WorkerStatus:
    """Status constants for swarm workers."""
    READY: Final = "ready"
    RUNNING: Final = "running"
    BLOCKED: Final = "blocked"
    COMPLETED: Final = "completed"
    FAILED: Final = "failed"
    TIMED_OUT: Final = "timed_out"


class WorkerHandle:
    """A handle to a worker registered in the swarm."""
    @property
    def worker_id(self) -> str: ...
    @property
    def prompt(self) -> str: ...
    @property
    def status(self) -> str: ...
    @property
    def started_at_secs(self) -> int | None: ...


class AgentReport:
    """A report submitted by a worker upon task completion."""
    @property
    def worker_id(self) -> str: ...
    @property
    def task_id(self) -> str | None: ...
    @property
    def status(self) -> str: ...
    @property
    def summary(self) -> str: ...


class SwarmSummaryReport:
    """Aggregate summary of all workers in the swarm."""
    @property
    def total_workers(self) -> int: ...
    @property
    def completed(self) -> int: ...
    @property
    def failed(self) -> int: ...
    @property
    def timed_out(self) -> int: ...
    @property
    def tasks_reassigned(self) -> int: ...
    @property
    def worker_reports(self) -> list[AgentReport]: ...
    def all_terminal(self) -> bool: ...
    def format(self) -> str: ...


class RetryPolicy:
    """Retry policy for swarm worker tasks."""
    def __init__(self, *, max_retries: int = 3, retry_delay_secs: int = 2, reassign_on_exhausted: bool = True, task_timeout_secs: int = 300, health_check_interval_secs: int = 5) -> None: ...
    @property
    def max_retries(self) -> int: ...
    @property
    def retry_delay_secs(self) -> int: ...
    @property
    def reassign_on_exhausted(self) -> bool: ...
    @property
    def task_timeout_secs(self) -> int: ...
    @property
    def health_check_interval_secs(self) -> int: ...


class SwarmCoordinator:
    """Central coordinator for swarm multi-agent orchestration."""
    def __init__(self) -> None: ...
    async def spawn(self, worker_id: str, prompt: str) -> WorkerHandle: ...
    async def list_workers(self) -> list[WorkerHandle]: ...
    async def await_members(self, expected_count: int, timeout_secs: int) -> list[WorkerHandle] | None: ...
    async def assign_next_task(self, worker_id: str) -> str | None: ...
    async def report_completion(self, worker_id: str, task_id: str, summary: str) -> AgentReport | None: ...
    async def reports(self) -> list[AgentReport]: ...
    async def broadcast(self, from_worker_id: str, content: str) -> None: ...


class SwarmSupervisor:
    """Supervisor that monitors worker health, handles retries, and generates summary reports."""
    def __init__(self, coordinator: SwarmCoordinator, policy: RetryPolicy) -> None: ...
    @staticmethod
    def with_defaults(coordinator: SwarmCoordinator) -> SwarmSupervisor: ...
    async def run_health_loop(self) -> None: ...
    async def generate_summary(self) -> SwarmSummaryReport: ...
    async def await_completion(self) -> SwarmSummaryReport: ...


# ── Event Constants ──────────────────────────────────────────────────────

class EventType:
    """Module-level dict of event type string constants."""
    TEXT_DELTA: Final = "text_delta"
    THINKING_DELTA: Final = "thinking_delta"
    TOOL_START: Final = "tool_start"
    TOOL_END: Final = "tool_end"
    TOOL_PROGRESS: Final = "tool_progress"
    USAGE: Final = "usage"
    ERROR: Final = "error"
    PERMISSION_REQUEST: Final = "permission_request"
    TURN_START: Final = "turn_start"
    TURN_END: Final = "turn_end"
    ARTIFACT_STORED: Final = "artifact_stored"
    ARTIFACT_READ: Final = "artifact_read"
    MCP_CONNECTED: Final = "mcp_connected"
    MCP_DISCONNECTED: Final = "mcp_disconnected"
    PLAN_PROGRESS: Final = "plan_progress"
