use async_trait::async_trait;
use futures::stream::BoxStream;
use serde::{Deserialize, Serialize};
use serde_json::Value;
use thiserror::Error;

use crate::message::Message;
use crate::tool::ToolDefinition;

/// Error type for provider-level failures (API errors, timeouts, etc.).
#[derive(Debug, Error, Clone)]
pub enum ProviderError {
    #[error("provider error: {message}")]
    Message { message: String },
}

impl ProviderError {
    /// Check whether this error is likely transient (retryable).
    ///
    /// Returns `true` for network errors, timeouts, 5xx server errors,
    /// rate-limit responses, and DNS failures.  Returns `false` for
    /// permanent errors like 4xx client errors (except 429), auth
    /// failures, and model-not-found.
    pub fn is_retryable(&self) -> bool {
        let msg = self.to_string().to_lowercase();

        // ── Network-level failures ──
        let network = msg.contains("timeout")
            || msg.contains("connection")
            || msg.contains("dns")
            || msg.contains("refused")
            || msg.contains("reset")
            || msg.contains("broken pipe")
            || msg.contains("eof")
            || msg.contains("unreachable")
            || msg.contains("network")
            || msg.contains("tls")
            || msg.contains("ssl")
            || msg.contains("resolve")
            || msg.contains("connect");

        // ── Server-side (5xx, overload) ──
        let server = msg.contains("503")
            || msg.contains("502")
            || msg.contains("504")
            || msg.contains("500")
            || msg.contains("529")
            || msg.contains("server")
            || msg.contains("service unavailable")
            || msg.contains("overloaded")
            || msg.contains("capacity")
            || msg.contains("busy")
            || msg.contains("internal server error")
            || msg.contains("bad gateway")
            || msg.contains("gateway timeout");

        // ── Rate limiting (429) ──
        let rate = msg.contains("429")
            || msg.contains("rate")
            || msg.contains("too many")
            || msg.contains("throttl");

        network || server || rate
    }
}

/// A boxed, fallible stream of events from a provider.
pub type EventStream = BoxStream<'static, Result<StreamEvent, ProviderError>>;

/// Events emitted during a streaming provider response.
#[derive(Debug, Clone)]
pub enum StreamEvent {
    /// A chunk of generated text
    TextDelta { text: String },
    /// A chunk of reasoning/thinking output (e.g. DeepSeek reasoning_content,
    /// Anthropic extended thinking). Displayed separately from the final text.
    ThinkingDelta { text: String },
    /// A tool-use request from the model
    ToolUse {
        id: String,
        name: String,
        input: Value,
    },
    /// A partial chunk of a tool-use request's input JSON, emitted while the
    /// arguments are still being streamed by the provider. `index` correlates
    /// deltas belonging to the same tool call within one response; `id` and
    /// `name` are populated once known (usually on the first delta). The full,
    /// parsed input still arrives later as a `ToolUse` event — these deltas
    /// are purely for progress display and do not drive tool execution.
    ToolInputDelta {
        index: usize,
        id: Option<String>,
        name: Option<String>,
        delta: String,
    },
    /// Token usage information (may appear mid-stream or at end)
    Usage { usage: TokenUsage },
    /// End of the response stream, with optional stop reason
    /// (e.g. "stop", "max_tokens", "tool_use", "length")
    MessageStop { stop_reason: Option<String> },
    /// Provider-side compaction notification.
    /// Emitted when the provider automatically compacts the context
    /// (e.g. Anthropic's context compaction).
    Compaction {
        trigger: String,
        pre_tokens: Option<u64>,
    },
    /// Connection type information (e.g. "proxy", "direct").
    ConnectionType { connection: String },
    /// Upstream provider routed by the gateway.
    UpstreamProvider { provider: String },
}

/// Token usage statistics from a provider response.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct TokenUsage {
    /// Tokens consumed by the input (prompt + messages)
    pub input_tokens: u32,
    /// Tokens generated by the model
    pub output_tokens: u32,
    /// Total tokens (input + output)
    pub total_tokens: u32,
    /// Cache read tokens (from prompt caching).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cache_read_input_tokens: Option<u32>,
    /// Cache creation tokens.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cache_creation_input_tokens: Option<u32>,
}

/// Abstract language model backend (OpenAI, Anthropic, OpenRouter, etc.).
#[async_trait]
pub trait Provider: Send + Sync {
    /// Send messages to the LLM and receive a streaming response.
    async fn complete(
        &self,
        model_id: &str,
        messages: &[Message],
        tools: &[ToolDefinition],
        system_static: &str,
        system_dynamic: &str,
        resume_session_id: Option<&str>,
    ) -> Result<EventStream, ProviderError>;

    /// Short name identifying this provider (e.g. "openai", "anthropic").
    fn name(&self) -> &str;

    /// Available model IDs for this provider.
    fn available_models(&self) -> Vec<String> {
        Vec::new()
    }

    /// Whether this provider handles tool execution internally
    /// (e.g. Claude Code CLI SDK). When true, the agent should not
    /// execute tools locally unless the tool is in the native set.
    fn handles_tools_internally(&self) -> bool {
        false
    }

    /// Whether this provider supports context compaction natively.
    fn supports_compaction(&self) -> bool {
        false
    }
}
