//! Wiki-style memory LLM semantic interface: query expansion / rerank / enrich / dedupe.
//!
//! [`WikiAssistant`] is the only seam through which the memory system uses the
//! LLM for wiki recall.  [`ProviderBackedWikiAssistant`] implements it with the
//! same provider + model_id as the primary agent (no external services), reusing
//! the `call_provider` pattern from [`super::relevance`].

use async_trait::async_trait;
use std::sync::Arc;

use crate::provider::Provider;
use crate::utils::truncate_to_bytes;

use super::relevance::call_provider;
use super::types::MemoryEntry;

/// LLM expansion of a user query into searchable terms.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct QueryExpansion {
    /// Normalized query terms.
    pub terms: Vec<String>,
    /// Synonyms / aliases / cross-language variants.
    pub aliases: Vec<String>,
    /// Named entities.
    pub entities: Vec<String>,
    /// Suggested tags.
    pub tags: Vec<String>,
    /// Natural-language rewrite (used for rerank / injection).
    pub natural_query: String,
}

impl QueryExpansion {
    /// Pure lexical fallback when the LLM is unavailable or disabled.
    pub fn from_query(query: &str) -> Self {
        let terms: Vec<String> = crate::memory::types::normalize_search_text(query)
            .split_whitespace()
            .filter(|t| t.len() > 1)
            .map(|t| t.to_string())
            .collect();
        Self {
            natural_query: query.trim().to_string(),
            terms,
            ..Default::default()
        }
    }

    pub fn is_empty(&self) -> bool {
        self.terms.is_empty()
            && self.aliases.is_empty()
            && self.entities.is_empty()
            && self.tags.is_empty()
    }

    /// All terms usable for lexical matching, deduplicated, preserving order.
    pub fn all_search_terms(&self) -> Vec<String> {
        let mut seen = std::collections::HashSet::new();
        self.terms
            .iter()
            .chain(self.aliases.iter())
            .chain(self.entities.iter())
            .chain(self.tags.iter())
            .filter(|t| !t.trim().is_empty())
            .filter(|t| seen.insert(t.to_lowercase()))
            .cloned()
            .collect()
    }
}

/// Enriched metadata generated by the assistant for a memory entry.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct EnrichedMemory {
    /// One-line wiki page title.
    pub title: String,
    /// One-sentence summary (used for index & injection).
    pub summary: String,
    pub tags: Vec<String>,
    pub aliases: Vec<String>,
    /// Hit existing entry ids (ordered by relevance) — the manager builds `[[links]]`.
    pub link_ids: Vec<String>,
}

/// Rerank result for a single candidate entry.
#[derive(Debug, Clone, PartialEq)]
pub struct RankedCandidate {
    pub id: String,
    /// Relevance score in 0.0–1.0.
    pub score: f32,
    pub reason: String,
}

/// Wiki-style memory LLM semantic interface.
#[async_trait]
pub trait WikiAssistant: Send + Sync {
    /// Expand a user query into searchable terms.
    async fn expand_query(&self, query: &str) -> Result<QueryExpansion, String>;

    /// Pick the subset of candidates most relevant to the query (with reasons).
    async fn rerank(
        &self,
        query: &str,
        candidates: &[MemoryEntry],
    ) -> Result<Vec<RankedCandidate>, String>;

    /// Generate title/summary/tags/aliases/links for an entry.
    async fn enrich(
        &self,
        entry: &MemoryEntry,
        existing_titles: &[String],
    ) -> Result<EnrichedMemory, String>;

    /// Decide whether two memories describe the same thing (LLM dedupe).
    async fn are_same(&self, a: &str, b: &str) -> Result<bool, String>;
}

// ── Provider-backed implementation ──

/// Default implementation using a Provider + model_id for LLM calls.
pub struct ProviderBackedWikiAssistant {
    provider: Arc<dyn Provider>,
    model_id: String,
}

impl ProviderBackedWikiAssistant {
    pub fn new(provider: Arc<dyn Provider>, model_id: impl Into<String>) -> Self {
        Self {
            provider,
            model_id: model_id.into(),
        }
    }
}

#[async_trait]
impl WikiAssistant for ProviderBackedWikiAssistant {
    async fn expand_query(&self, query: &str) -> Result<QueryExpansion, String> {
        let system = r#"You are a memory search query expander for a wiki-style knowledge base.
Rewrite the user's query into searchable terms that would appear in stored memory entries.

Output each section on its own line in this exact format:
TERMS: term1, term2, term3
ALIASES: alias1, alias2
ENTITIES: entity1, entity2
TAGS: tag1, tag2
NATURAL: <a natural-language rewrite of the query>

Rules:
- TERMS: the 2-6 most important normalized keywords/phrases (lowercase, no punctuation)
- ALIASES: synonyms, abbreviations, or cross-language variants of the terms
- ENTITIES: proper nouns (people, projects, libraries, domains) mentioned or implied
- TAGS: 0-3 category-style tags that memory entries might carry
- NATURAL: one concise natural-language rewrite
Output ONLY the formatted lines."#;
        let response = call_provider(&*self.provider, &self.model_id, system, query).await?;
        Ok(parse_query_expansion(&response, query))
    }

    async fn rerank(
        &self,
        query: &str,
        candidates: &[MemoryEntry],
    ) -> Result<Vec<RankedCandidate>, String> {
        let mut user = format!("## Query\n{query}\n\n## Candidates\n");
        for (i, c) in candidates.iter().enumerate() {
            let title = c.title.clone().unwrap_or_else(|| "[no title]".to_string());
            let summary = c.summary.clone().unwrap_or_default();
            user.push_str(&format!(
                "{}. {}\n",
                i + 1,
                truncate_to_bytes(&format!("{title} | {summary}"), 220)
            ));
        }
        let system = r#"You are a memory relevance reranker. Given a query and a numbered list of candidate memories, rank them by relevance to the query.
Output one line per candidate in this exact format:
ID|SCORE|REASON
- ID must be exactly the id of the candidate entry (the id is not shown above, use the candidate index as the id: "1", "2", ...)
- SCORE is a float from 0.0 (irrelevant) to 1.0 (highly relevant)
- REASON is a short phrase (no pipes)
Output ONLY the formatted lines, ordered best first. If nothing is relevant, output nothing."#;
        let response = call_provider(&*self.provider, &self.model_id, system, &user).await?;
        Ok(parse_rerank_output(&response))
    }

    async fn enrich(
        &self,
        entry: &MemoryEntry,
        existing_titles: &[String],
    ) -> Result<EnrichedMemory, String> {
        let mut system = String::from(
            r#"You are a knowledge-base editor. Turn a raw memory entry into a concise wiki page record.
Output each field on its own line in this exact format:
TITLE: <one-line page title, noun phrase, <= 80 chars>
SUMMARY: <one sentence summarizing the memory, <= 160 chars>
TAGS: tag1, tag2, tag3
ALIASES: alias1, alias2
LINKS: <ids of the most related existing entries, 0-5 ids, comma separated, use the candidate index ids from the list below>
Output ONLY the formatted lines."#,
        );
        if !existing_titles.is_empty() {
            system.push_str("\n\nExisting entries (numbered titles):\n");
            for (i, t) in existing_titles.iter().take(80).enumerate() {
                system.push_str(&format!("{}. {}\n", i + 1, truncate_to_bytes(t, 120)));
            }
        }
        let user = format!(
            "## Memory Content\n{}\n\nCategory: {}",
            entry.content, entry.category
        );
        let response = call_provider(&*self.provider, &self.model_id, &system, &user).await?;
        Ok(parse_enrich_output(&response))
    }

    async fn are_same(&self, a: &str, b: &str) -> Result<bool, String> {
        let system = "You are a deduplication judge. Decide whether the two statements describe the same underlying fact or preference. Reply with exactly YES or NO.";
        let prompt = format!(
            "## Statement A\n{a}\n\n## Statement B\n{b}\n\nDo A and B describe the same thing?"
        );
        let response = call_provider(&*self.provider, &self.model_id, system, &prompt).await?;
        Ok(response.trim().to_uppercase().starts_with("YES"))
    }
}

// ── Defensive line-format parsers ──

/// Extract the comma-separated value list of a `LABEL: a, b, c` line.
fn parse_field(response: &str, label: &str) -> Vec<String> {
    response
        .lines()
        .find_map(|line| {
            let (head, rest) = line.trim().split_once(':')?;
            if !head.trim().eq_ignore_ascii_case(label) {
                return None;
            }
            Some(rest)
        })
        .map(|rest| {
            rest.split(',')
                .map(|s| s.trim().trim_matches('"').trim_matches('\'').to_string())
                .filter(|s| !s.is_empty())
                .collect()
        })
        .unwrap_or_default()
}

/// Extract the text value of a `LABEL: value` line.
fn parse_field_text(response: &str, label: &str) -> String {
    response
        .lines()
        .find_map(|line| {
            let line = line.trim();
            let (head, rest) = line.split_once(':')?;
            if !head.trim().eq_ignore_ascii_case(label) {
                return None;
            }
            Some(rest.trim().to_string())
        })
        .unwrap_or_default()
}

/// Parse `expand_query` output into a [`QueryExpansion`].
///
/// Falls back to the original query as `natural_query` when the LLM omitted
/// the `NATURAL` line.
pub fn parse_query_expansion(response: &str, fallback_query: &str) -> QueryExpansion {
    let natural = parse_field_text(response, "NATURAL");
    QueryExpansion {
        terms: parse_field(response, "TERMS"),
        aliases: parse_field(response, "ALIASES"),
        entities: parse_field(response, "ENTITIES"),
        tags: parse_field(response, "TAGS"),
        natural_query: if natural.is_empty() {
            fallback_query.trim().to_string()
        } else {
            natural
        },
    }
}

/// Parse `rerank` output (`ID|SCORE|REASON` lines) into ranked candidates,
/// deduplicated by id (keeping the highest score) and sorted best-first.
pub fn parse_rerank_output(response: &str) -> Vec<RankedCandidate> {
    let mut seen: std::collections::HashMap<String, RankedCandidate> =
        std::collections::HashMap::new();
    for line in response.lines() {
        let mut parts = line.split('|');
        let id = parts
            .next()
            .map(|s| s.trim().to_string())
            .unwrap_or_default();
        if id.is_empty() {
            continue;
        }
        // Skip malformed lines whose score cannot be parsed.
        let Some(score) = parts.next().and_then(|s| s.trim().parse::<f32>().ok()) else {
            continue;
        };
        let score = score.clamp(0.0, 1.0);
        let reason = parts.next().unwrap_or("").trim().to_string();
        let candidate = RankedCandidate {
            id: id.clone(),
            score,
            reason,
        };
        seen.entry(id)
            .and_modify(|c| {
                if score > c.score {
                    *c = candidate.clone();
                }
            })
            .or_insert(candidate);
    }
    let mut out: Vec<RankedCandidate> = seen.into_values().collect();
    out.sort_by(|a, b| {
        b.score
            .partial_cmp(&a.score)
            .unwrap_or(std::cmp::Ordering::Equal)
    });
    out
}

/// Parse `enrich` output (`TITLE/SUMMARY/TAGS/ALIASES/LINKS` lines) into an
/// [`EnrichedMemory`].  Missing fields default to empty values.
pub fn parse_enrich_output(response: &str) -> EnrichedMemory {
    EnrichedMemory {
        title: parse_field_text(response, "TITLE"),
        summary: parse_field_text(response, "SUMMARY"),
        tags: parse_field(response, "TAGS"),
        aliases: parse_field(response, "ALIASES"),
        link_ids: parse_field(response, "LINKS"),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::memory::types::{MemoryCategory, MemoryEntry};
    use crate::message::Message;
    use crate::provider::{EventStream, ProviderError, StreamEvent};
    use crate::tool::ToolDefinition;
    use futures::stream;

    struct MockProvider {
        response: String,
    }

    #[async_trait]
    impl Provider for MockProvider {
        async fn complete(
            &self,
            _model_id: &str,
            _messages: &[Message],
            _tools: &[ToolDefinition],
            _system_static: &str,
            _system_dynamic: &str,
            _resume_session_id: Option<&str>,
        ) -> Result<EventStream, ProviderError> {
            let text = self.response.clone();
            Ok(Box::pin(stream::iter(vec![Ok(StreamEvent::TextDelta {
                text,
            })])))
        }

        fn name(&self) -> &str {
            "mock"
        }
    }

    fn assistant(response: &str) -> ProviderBackedWikiAssistant {
        ProviderBackedWikiAssistant::new(
            Arc::new(MockProvider {
                response: response.to_string(),
            }),
            "mock-model",
        )
    }

    #[test]
    fn query_expansion_from_query_uses_lexical_terms() {
        let exp = QueryExpansion::from_query("  Rust Error Handling  ");
        assert_eq!(exp.natural_query, "Rust Error Handling");
        assert_eq!(exp.terms, vec!["rust", "error", "handling"]);
        assert!(exp.aliases.is_empty());
        assert!(!exp.is_empty());
    }

    #[test]
    fn query_expansion_is_empty_for_blank_query() {
        assert!(QueryExpansion::from_query("   ").is_empty());
    }

    #[test]
    fn query_expansion_all_search_terms_deduplicates() {
        let exp = QueryExpansion {
            terms: vec!["rust".into(), "rust".into()],
            aliases: vec!["rs".into()],
            entities: vec!["cargo".into()],
            tags: vec!["tooling".into()],
            natural_query: "rust".into(),
        };
        assert_eq!(
            exp.all_search_terms(),
            vec!["rust", "rs", "cargo", "tooling"]
        );
    }

    #[test]
    fn parse_query_expansion_handles_all_fields_and_missing_lines() {
        let response = "TERMS: rust, error handling\nALIASES: rs\nENTITIES: cargo\nNATURAL: how to handle errors in rust";
        let exp = parse_query_expansion(response, "original");
        assert_eq!(exp.terms, vec!["rust", "error handling"]);
        assert_eq!(exp.aliases, vec!["rs"]);
        assert_eq!(exp.entities, vec!["cargo"]);
        assert!(exp.tags.is_empty());
        assert_eq!(exp.natural_query, "how to handle errors in rust");

        // Missing NATURAL falls back to the original query.
        let exp2 = parse_query_expansion("TERMS: a", "original query");
        assert_eq!(exp2.natural_query, "original query");
    }

    #[test]
    fn parse_query_expansion_is_case_insensitive_and_quotes_tolerant() {
        let exp = parse_query_expansion("terms: \"a\", 'b', c", "q");
        assert_eq!(exp.terms, vec!["a", "b", "c"]);
    }

    #[test]
    fn parse_rerank_output_sorts_and_dedupes_by_id() {
        let response = "2|0.9|very relevant\n1|0.3|meh\n1|0.95|better reason";
        let ranked = parse_rerank_output(response);
        assert_eq!(ranked.len(), 2);
        assert_eq!(ranked[0].id, "1");
        assert_eq!(ranked[0].score, 0.95);
        assert_eq!(ranked[1].id, "2");
        assert_eq!(ranked[1].score, 0.9);
    }

    #[test]
    fn parse_rerank_output_clamps_score_and_skips_garbage() {
        let ranked = parse_rerank_output("x|2.5|high\n\ny|abc|bad\nz|0.0|none");
        assert_eq!(ranked.len(), 2);
        assert_eq!(ranked[0].id, "x");
        assert_eq!(ranked[0].score, 1.0);
        assert_eq!(ranked[1].score, 0.0);
    }

    #[test]
    fn parse_enrich_output_parses_all_fields() {
        let response = "TITLE: Rust error handling\nSUMMARY: Prefer Result over panic\nTAGS: rust, errors\nALIASES: rs\nLINKS: mem_a, mem_b";
        let e = parse_enrich_output(response);
        assert_eq!(e.title, "Rust error handling");
        assert_eq!(e.summary, "Prefer Result over panic");
        assert_eq!(e.tags, vec!["rust", "errors"]);
        assert_eq!(e.aliases, vec!["rs"]);
        assert_eq!(e.link_ids, vec!["mem_a", "mem_b"]);
    }

    #[tokio::test]
    async fn provider_backed_assistant_expand_query_end_to_end() {
        let a = assistant(
            "TERMS: snake case, naming\nALIASES: snake_case\nNATURAL: how to name things",
        );
        let exp = a.expand_query("python naming convention").await.unwrap();
        assert_eq!(exp.terms, vec!["snake case", "naming"]);
        assert_eq!(exp.aliases, vec!["snake_case"]);
        assert_eq!(exp.natural_query, "how to name things");
    }

    #[tokio::test]
    async fn provider_backed_assistant_rerank_end_to_end() {
        let a = assistant("2|0.9|match\n1|0.4|partial");
        let c1 = MemoryEntry::new(MemoryCategory::Preference, "one");
        let c2 = MemoryEntry::new(MemoryCategory::Preference, "two");
        let ranked = a.rerank("query", &[c1, c2]).await.unwrap();
        assert_eq!(ranked.len(), 2);
        assert_eq!(ranked[0].score, 0.9);
    }

    #[tokio::test]
    async fn provider_backed_assistant_enrich_and_are_same_end_to_end() {
        let a = assistant("TITLE: Tabs\nSUMMARY: Use tabs for indentation");
        let entry = MemoryEntry::new(MemoryCategory::Preference, "Use tabs");
        let enriched = a.enrich(&entry, &["Spaces".to_string()]).await.unwrap();
        assert_eq!(enriched.title, "Tabs");
        assert_eq!(enriched.summary, "Use tabs for indentation");
        assert!(enriched.link_ids.is_empty());

        let a2 = assistant("YES");
        assert!(a2.are_same("Use tabs", "Tabs are preferred").await.unwrap());
    }
}
